Add donors scraping CGI scripts
qgis/QGIS-Website pull request #442
Opened 2024-09-23 11:35 UTC by Xpirix

2024-09-24 10:50 UTC, timlinux commented
Let me chat with @andreasneumann a bit about this - I am not too mad about turning our static site back into a dynamic site. Maybe we can implement this on a GH action rather or on a server that is not exposed to the internet....

2025-01-21 11:42 UTC, timlinux commented
Can we not do this as a gh action rather to do the scraping and update the deployment bundle (when we have teh site as a nixos package) e.g. once a day?

2025-01-21 11:43 UTC, timlinux requested changes
I think we need to find another way e.g. as a gh action. I don't want to run code and cgi scripts on our server.

2025-01-27 12:39 UTC, Xpirix commented
## Latest Updates according to previous comments

- Added a script `update_donors.py`: it fetches new donors from Stripe API and updates the donors list accordingly.
- Run `update_donors.py` in GitHub actions with the `update-donors.yml` workflow
- The script requires the variable `STRIPE_API_KEY` from the secrets
- The schedule is similar to the update feed workflow, i.e each day at noon (UTC)

2025-01-28 11:49 UTC, timlinux approved these changes
LGTM

2025-01-30 11:07 UTC, timlinux approved these changes
LGTM

2025-01-30 11:47 UTC, merged